### ISSUE TITLE
Does not duplicate a HasOne

### ISSUE THREAD

**Issue by birdy247** [riesenia/cakephp-duplicatable#17]
A lesson HasOne Prices

The issue is cake php shows this as "price" in the entity not "prices".  So the behaviour is not able to find the property with $entity->{Inflector::tableize($matches[1])} (because this is using the plural not singular name.

Should a proper fix be to look at the actual property name rather than assuming a property name?

**Comment by segy** [comment]
hope this was fixed by @ADmad
