### ISSUE TITLE
Duplicate nested contains trigger AfterSave events

### ISSUE THREAD

**Issue by Greyg-POPEI** [riesenia/cakephp-duplicatable#28]
Hello,

I would like to use your plugin for duplicate a Survey table.

This survey table has to many sections, which have to many questions etc...
Some of my relations have in their model, an AfterSave Event..

This AfterSave event is triggered when I try to use your plugin, who cause some duplicates data...

Their is a way to prevent activation of these events ? 

Thank you and have a good day

**Comment by segy** [comment]
Hi

not sure what exactly you're trying to achieve. Note there is a configuration key `saveOptions`. Options passed to `save` are passed to all events, so I'd guess to add something (anything) there and modify your callbacks. There probably is a problem in them when they create duplicate data.

Regards
