### ISSUE TITLE
Feature Enhancement for // set / prepend / append

### ISSUE THREAD

**Issue by akkaweb** [riesenia/cakephp-duplicatable#3]
Really cool plugin that works really well!

I have one enhancement suggestion.

Currently `// set / prepend / append` is designed to only accept one field. It would be a great feature addition to allow them more than one field.

In my application I am circumventing this by using `append` and `prepend` when I really just wanted to use `append`.

```
$this->addBehavior('Duplicatable.Duplicatable', [
    'set' => ['duplicated' => true],
    'append' => ['title' => ' - copy'],
    'prepend' => ['slug' => 'copy-']
]);`
```

Preferably I wanted to do this

```
$this->addBehavior('Duplicatable.Duplicatable', [
    'set' => ['duplicated' => true],
    'append' => ['title' => ' - copy', 'slug' => '-copy'],
]);`
```

**Comment by ypnos-web** [comment]
`set`, `prepend` and `append` options already accept several fields. See [here](https://github.com/riesenia/cakephp-duplicatable/blob/64e7da786d4ee44b55a63fcd008cf013c686c8c4/src/Model/Behavior/DuplicatableBehavior.php#L136).

You can also see several fields passed to `set` in the [example](https://github.com/riesenia/cakephp-duplicatable#examples).

**Comment by segy** [comment]
hope I can close this now. thanks @ypnos-web
