### ISSUE TITLE
Possible to use contain all

### ISSUE THREAD

**Issue by LubosRemplik** [riesenia/cakephp-duplicatable#32]
Is it possible / is it good idea to make it possible to have something like contain => all with behavior config so we don't have to set associations again which are known from table config?

**Comment by segy** [comment]
Possible... sure. I can’t think of any use case where this would help me, but if you find it useful, PR is welcome.

**Comment by LubosRemplik** [comment]
Well when I am thinking about it more, not sure if useful because there are usually some associations which you don't want to duplicate, e.g. CreatedBy and ModifiedBy

So either ignore this or do you think it would be useful to do something like

```
// include all associations
'containAll': true

// include all associations exclude the one in the array
'containAll': [
    'CreatedBy',
    'ModifiedBy'
]
```
