### ISSUE TITLE
Typo in _getFinder's DocBlock makes IDE show a problem

### ISSUE THREAD

**Issue by hacheraw** [riesenia/cakephp-duplicatable#51]
```php
/**
 * Return finder to use for fetching entities.
 *
 * @param string|null $assocPath Dot separated association path. E.g. Invoices.InvoiceItems
 * @return string
 */
protected function _getFinder($assocPath = null)
{
```

This should be 

```php
@return array
```

As this method actually returns an array wich is iterated in other methods

I'd be glad to open a PR but since this affects to 3.x and master, I don't know how to proceed. Should it be one PR or two?

**Comment by ADmad** [comment]
Two PRs would be nice :)

**Comment by hacheraw** [comment]
PR made. I was mistaken. It only affects to 3.x so only one PR is required: #52
